package com.bobbyesp.mediaplayer.domain.model

import android.os.Parcelable
import androidx.compose.runtime.Immutable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Serializable

/**
 * Data class representing a music track.
 *
 * @property id Unique ID (can be generated by MediaStore or a hash).
 * @property title Title of the song.
 * @property artist Artist of the song.
 * @property album Album of the song.
 * @property genre Genre of the song (can be null if not available).
 * @property duration Duration of the song in milliseconds.
 * @property trackNumber Track number in the album (if available).
 * @property discNumber Disc number (for albums with multiple discs).
 * @property year Year of release.
 * @property lyrics Lyrics of the song (if available).
 * @property path Full path of the file in storage.
 * @property artworkUri URI of the album artwork.
 * @property addedTimestamp Date when the song was added to the library.
 * @property modifiedTimestamp Last modification date of the file.
 * @property size Size of the file in bytes.
 * @property trackTechnicalDetails Technical details of the track (bitrate, sample rate, channels).
 */
@Parcelize
@Immutable
@Serializable
data class MusicTrack(
    val id: Long,
    val title: String,
    val artist: String? = null,
    val album: String? = null,
    val genre: String? = null,
    val duration: Long? = null,
    val trackNumber: Int? = null,
    val discNumber: Int? = null,
    val year: Int? = null,
    val lyrics: String? = null,
    val path: String,
    val artworkUri: String? = null,
    val addedTimestamp: Long? = null,
    val modifiedTimestamp: Long? = null,
    val size: Long? = null,
    val trackTechnicalDetails: TrackTechnicalDetails? = null,
) : Parcelable
