# From https://github.com/JunkFood02/Seal
name: Android CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> local.properties
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> local.properties

      - name: Create Google Service file
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -d > app/google-services.json

      - uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleFoss

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Metadator-${{ github.sha }}.apk
          path: app/build/outputs/apk/foss/*.apk
