name: Android CI

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-debug:
    name: Build FOSS APKs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Create local.properties
        run: |
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> local.properties
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> local.properties

      - uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        env:
            ENCODED_KEYSTORE_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
        run: |
          base64 -d <<< $ENCODED_KEYSTORE_STRING > ./keystore.jks
          echo "RELEASE_STORE_FILE=$(realpath ./keystore.jks)" >> $GITHUB_ENV

      - name: Build with Gradle
        env:
          SIGNING_KEY_STORE_PATH: ${{ env.RELEASE_STORE_FILE }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew assembleFoss

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
            name: release-artifacts
            paths: |
              app/build/outputs/apk/release/
              app/build/outputs/apk/debug/